apiVersion: 1

datasources:
  - name: GlowPipe-Streaming
    type: postgres
    uid: glowpipe_pg
    url: streaming_postgres:5432
    database: glowpipe_streaming
    user: grafana_reader
    secureJsonData:
      password: grafana_readonly_pw
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1300
      timescaledb: false
    isDefault: true
    editable: true
